spring:
  profiles:
  active:
  - dev
---
server:
  port: 7000
spring:
  profiles: dev
  redis:
    host: 192.168.226.129
    port: 6379
  application:
    name: scw-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.226.129:3306/atcrowdfunding
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.lichen.scw.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client: # 将该服务注册进eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
  
---
server:
  port: 8000
spring:
  profiles: dev
  redis:
    host: 192.168.226.129
    port: 6379
  application:
    name: scw-project
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.226.129:3306/atcrowdfunding
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.lichen.scw.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client: # 将该服务注册进eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    
---
server:
  port: 8000
spring:
  profiles: dev
  redis:
    host: 192.168.226.129
    port: 6379
  application:
    name: scw-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.226.129:3306/atcrowdfunding
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.lichen.scw.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client: # 将该服务注册进eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true