spring:
  profiles:
  active:
  - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: scw-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: scw-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/